config/routes.rb
Rails.application.routes.draw do
  resources :packing_lists do
    member do
      get 'copy'
    end
  end
  resources :gears
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :gears
  validates :name, presence: true
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :title, presence: true
  validates :name, presence: true
  validates :weight, presence: true, numericality: true
  validates :user, presence: true
  validates :category, presence: true

  mount_uploader :image, ImageUploader

  scope :by_category, ->(category_id) { where(category_id: category_id) }

  def display_name
    "【#{category.name}】#{title} / #{name}"
  end
end

app/models/packing_list.rb
class PackingList < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :user, presence: true

  mount_uploader :image, ImageUploader

  has_many :packing_list_gears, ->{ joins(:gear).order('gears.category_id asc, gears.title asc') }, inverse_of: :packing_list, dependent: :destroy
  has_many :gears, ->{ order(category_id: :asc, title: :asc) }, through: :packing_list_gears

  accepts_nested_attributes_for :packing_list_gears, allow_destroy: true
  REGISTRABLE_ATTRIBUTES = %i(title comment public image)

  scope :publish, -> { where(public: true) }

  def total_weight
    self.gears.map(&:weight).sum
  end

  def total_weight_by_category(category)
    self.gears.by_category(category).map(&:weight).sum
  end

  def copy
    copy = self.dup
    copy.title = "#{self.title}のコピー"
    copy.public = false
    copy.remove_image!
    self.gears.each do |gear|
      copy.gears << gear
    end
    copy
  end
end

app/models/packing_list_gear.rb
class PackingListGear < ApplicationRecord
  belongs_to :packing_list
  belongs_to :gear
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  has_many :packing_lists, dependent: :delete_all
  has_many :gears, -> { order(category_id: :asc, title: :asc) }, dependent: :delete_all

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, only: [:show, :edit, :update, :destroy]

  def index
    @search = current_user.gears.order(category_id: :asc, title: :asc).search(params[:q])
    @gears = @search.result
  end

  def show
  end

  def new
    @gear = current_user.gears.new
  end

  def edit
  end

  def create
    @gear = current_user.gears.new(gear_params)

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @gear, notice: 'Gear was successfully created.' }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gear.update(gear_params)
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: 'Gear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_gear
      @gear = Gear.find(params[:id])
    end

    def gear_params
      params.require(:gear).permit(:category_id, :image, :title, :name, :detail, :weight, :comment)
    end
end

app/controllers/packing_lists_controller.rb
class PackingListsController < ApplicationController
  before_action :set_packing_list, only: [:show, :edit, :update, :destroy, :copy]

  # GET /packing_lists
  # GET /packing_lists.json
  def index
    @packing_lists = current_user.packing_lists.all.order(updated_at: :desc)
  end

  # GET /packing_lists/1
  # GET /packing_lists/1.json
  def show
  end

  # GET /packing_lists/new
  def new
    @packing_list = current_user.packing_lists.new
  end

  # GET /packing_lists/1/edit
  def edit
  end

  # POST /packing_lists
  # POST /packing_lists.json
  def create
    @packing_list = current_user.packing_lists.new(packing_list_params)

    respond_to do |format|
      if @packing_list.save
        format.html { redirect_to @packing_list, notice: 'Packing list was successfully created.' }
        format.json { render :show, status: :created, location: @packing_list }
      else
        format.html { render :new }
        format.json { render json: @packing_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packing_lists/1
  # PATCH/PUT /packing_lists/1.json
  def update
    respond_to do |format|
      if @packing_list.update(packing_list_params)
        format.html { redirect_to @packing_list, notice: 'Packing list was successfully updated.' }
        format.json { render :show, status: :ok, location: @packing_list }
      else
        format.html { render :edit }
        format.json { render json: @packing_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packing_lists/1
  # DELETE /packing_lists/1.json
  def destroy
    @packing_list.destroy
    respond_to do |format|
      format.html { redirect_to packing_lists_url, notice: 'Packing list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def copy
    copy_packinglist = @packing_list.copy
    copy_packinglist.save
    redirect_to packing_lists_url, notice: 'Packing list was successfully copied.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_packing_list
    @packing_list = PackingList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def packing_list_params
    params.require(:packing_list).permit( PackingList::REGISTRABLE_ATTRIBUTES + [gear_ids: []])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @packing_lists = PackingList.all.publish.order(updated_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/packing_lists_helper.rb
module PackingListsHelper
  def display_public(public)
    public ? '公開' : '非公開'
  end
end

app/views/gears/_form.html.haml
= simple_form_for(@gear) do |f|
  = f.error_notification

  .form-inputs
    = f.association :category
    = image_tag f.object.image.thumb.url unless f.object.image.thumb.url.nil?
    = f.input :image, as: :file
    = f.input :title
    = f.input :name
    = f.input :detail
    = f.input :weight
    = f.input :comment

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/gears/edit.html.haml
%h2 道具の編集

= render 'form'

= link_to t('link.Show'), @gear
\|
= link_to t('link.Back'), gears_path

app/views/gears/index.html.haml
%h2 道具一覧
= link_to '道具を登録する', new_gear_path, class: 'btn btn-primary'
.gear-search
  = search_form_for @search, html: { class: 'navbar-form navbar-left' } do |f|
    = f.input :category_id_eq, collection: Category.all, label: false, include_blank: true
    = f.input :name_cont, label: false, placeholder: '品名'
    = f.submit '検索', class: 'btn btn-primary'

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th= sort_link @search, :category_id, t('activerecord.attributes.gear.category')
      %th= t('activerecord.attributes.gear.image')
      %th= sort_link @search, :weight, t('activerecord.attributes.gear.weight')
      %th= t('activerecord.attributes.gear.title')
      %th= t('activerecord.attributes.gear.name')
      %th= t('activerecord.attributes.gear.detail')
      %th= t('activerecord.attributes.gear.comment')
      %th
      %th
  %tbody
    - @gears.each do |gear|
      %tr
        %td= gear.category.name
        %td= image_tag gear.image.thumb.url unless gear.image.thumb.url.nil?
        %td.text-right
          = gear.weight
        %td= gear.title
        %td= gear.name
        %td= gear.detail
        %td= gear.comment
        %td= link_to t('link.Edit'), edit_gear_path(gear)
        %td= link_to t('link.Destroy'), gear, method: :delete, data: { confirm: t('link.confirm.delete') }

= link_to '道具を登録する', new_gear_path, class: 'btn btn-primary'

app/views/gears/new.html.haml
%h2 新しい道具の登録

= render 'form'

= link_to t('link.Back'), gears_path

app/views/gears/show.html.haml
%table.table.table-bordered
  %tr
    %td
      = t('activerecord.attributes.gear.category')
    %td
      = @gear.category.name
  %tr
    %td
      = t('activerecord.attributes.gear.image')
    %td
      = image_tag @gear.image, width: '240'
  %tr
    %td
      = t('activerecord.attributes.gear.title')
    %td
      = @gear.title
  %tr
    %td
      = t('activerecord.attributes.gear.name')
    %td
      = @gear.name
  %tr
    %td
      = t('activerecord.attributes.gear.detail')
    %td
      = @gear.detail
  %tr
    %td
      = t('activerecord.attributes.gear.weight')
    %td
      = @gear.weight
  %tr
    %td
      = t('activerecord.attributes.gear.comment')
    %td
      = @gear.comment

= link_to t('link.Edit'), edit_gear_path(@gear)
\|
= link_to t('link.Back'), gears_path
\|
= link_to '道具を登録する', new_gear_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    %li= link_to 'アカウント情報修正', edit_user_registration_path
    %li= link_to 'サインアウト', destroy_user_session_path, :method=>'delete'
  - else
    %li= link_to 'サインイン', new_user_session_path
    -#%li= link_to 'Sign up', new_user_registration_path
  - if user_signed_in? && current_user.admin?
    %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      = render 'layouts/navigation_links'
      = render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.haml
%ul.nav.navbar-nav
  - if user_signed_in?
    %li
      = link_to '私のパッキングリスト', packing_lists_path
    %li
      = link_to '私の道具たち', gears_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : '山のパッキングリスト'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : '山のパッキングリスト'}"}
    = stylesheet_link_tag 'application', media: 'all'
    -#= javascript_include_tag 'application'
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield
    = javascript_include_tag 'application'

app/views/packing_lists/_form.html.haml
= simple_form_for(@packing_list) do |f|
  = f.error_notification

  .form-inputs
    = f.input :public
    = image_tag f.object.image.thumb.url unless f.object.image.url.nil?
    = f.input :image, as: :file
    = f.input :title
    = f.input :comment
  %hr/
  .form-group
    .checkbox
      = f.collection_check_boxes :gear_ids, current_user.gears.all, :id, :display_name, boolean_style: :inline do |b|
        .view-select-gears
          - unless Gear.find(b.value).image.thumb.url.nil?
            = b.label { b.check_box + "#{image_tag(Gear.find(b.value).image.thumb.url , width: '60')}".html_safe + b.text  }
          - else
            = b.label { b.check_box + b.text  }

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/packing_lists/edit.html.haml
%h2 パッキングリストの編集

= render 'form'

= link_to t('link.Show'), @packing_list
\|
= link_to '一覧へ', packing_lists_path

app/views/packing_lists/index.html.haml
%h2 パッキングリスト一覧

.pull-right
  = link_to t('link.New'), new_packing_list_path, class: 'btn btn-primary'

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th= t('activerecord.attributes.packing_list.public')
      %th= t('activerecord.attributes.packing_list.updated_at')
      %th= t('activerecord.attributes.packing_list.image')
      %th= t('activerecord.attributes.packing_list.title')
      %th= t('activerecord.attributes.packing_list.comment')
      %th
      %th
      %th

  %tbody
    - @packing_lists.each do |packing_list|
      %tr
        %td= display_public(packing_list.public)
        %td= l packing_list.updated_at.to_date
        %td= image_tag packing_list.image.thumb.url unless packing_list.image.thumb.url.nil?
        %td= link_to packing_list.title, packing_list
        %td= packing_list.comment
        %td= link_to t('link.Edit'), edit_packing_list_path(packing_list)
        %td= link_to t('link.Copy'), copy_packing_list_path(packing_list)
        %td= link_to t('link.Destroy'), packing_list, method: :delete, data: { confirm: t('link.confirm.delete') }

app/views/packing_lists/new.html.haml
%h2 新しいパッキングリスト

= render 'form'

= link_to t('link.Back'), packing_lists_path

app/views/packing_lists/show.html.haml
.row
  .col-sm-6
    %h2= @packing_list.title
    %p= simple_format(@packing_list.comment)
    %h4.margin-top-30
      = "合計：#{@packing_list.total_weight} g"
  .col-sm-6
    = image_tag @packing_list.image.eye_catch.url unless @packing_list.image.eye_catch.url.nil?
.row
  .col-sm-12
    %table.table.table-list
      %thead
        %tr
          %th
          %th= t('activerecord.attributes.gear.weight')
          %th= t('activerecord.attributes.gear.title')
          %th= t('activerecord.attributes.gear.name')
          %th= t('activerecord.attributes.gear.detail')
      %tbody
        - Category.all.each do |category|
          %tr
            %td{colspan: 5}
              %h4.margin-top-30
                = "#{category.name} ： #{@packing_list.total_weight_by_category(category)} g"
          - @packing_list.gears.by_category(category).each do |gear|
            %tr
              - unless gear.image.thumb.url.nil?
                %td= link_to image_tag(gear.image.thumb.url, width: '60'), gear.image.url, data: {lightbox: 'gear-set', title: gear.title}
              - else
                %td
              %td.text-right
                = gear.weight
              %td= gear.title
              %td= gear.name
              %td= gear.detail
.row
  .col-sm-12
    %h3
      = "合計：#{@packing_list.total_weight} g"
  - if @packing_list.user == current_user
    = link_to t('link.Edit'), edit_packing_list_path(@packing_list), class: 'btn btn-primary'
    \|
    = link_to t('link.Index'), packing_lists_path

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.haml
%td= link_to user.name, user
%td= link_to user.email, user
%td
  = simple_form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    = f.submit 'Change Role', :class => 'button-xs'
%td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}

app/views/visitors/index.html.haml
.container
  .row
    .col-lg-12
      %h1.page-header
        山のパッキングリスト
  .row.row-eq-height
    - @packing_lists.each do |packing_list|
      .col-md-4.portfolio-item
        - if packing_list.image.eye_catch.present?
          = link_to image_tag(packing_list.image.eye_catch.url class: 'img-responsive'), packing_list.image.url, data: {lightbox: 'example-set', title: packing_list.title}
        - else
          = image_tag "http://placehold.it/320x240", class: 'img-responsive'
        %h4
          = l packing_list.updated_at.to_date
          %span{style: "font-size: 13px;"}更新
        %h3= packing_list.title
        %h4
          = packing_list.user.name
          %span{style: "font-size: 13px;"}さん
        %p= simple_format(packing_list.comment)
        = link_to packing_list, class: 'btn btn-primary' do
          View Packing
          %span.glyphicon.glyphicon-chevron-right
  %hr/
  %footer
    .row
      .col-lg-12
        %p Copyright © Yukibou 2016